Fixed compilation error "error: stray ‘\357’ in program" in several configuration files.
Introduced in commit 697ee2dc and later spread to other files.